### ISSUE TITLE
資料ダウンロード用ページを作る

### ISSUE THREAD

**Issue by pikotea** [html5j/events#104]
スポンサー向け（とくにアクセスコントロールはかけない）

各セッションの資料リンクを一覧にしたページを作る
最初は「準備中」で良い。

URLは

CONFERENCE_HOME/slides とか？

**Comment by myakura** [comment]
https://github.com/html5j/events/commit/4245bfa4ad9edaaf6b40fd0288aad231919d3dbb にて対応済
